[project]
name = "multi-agent-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.3.8",
    "openai>=2.9.0",
    "python-dotenv>=1.2.1",
]

[tool.uv.workspace]
members = [
    "Backend",
]
